TrashCollector/TrashCollector/Controllers/CustomersController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using Microsoft.AspNet.Identity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using TrashCollector.Models;
using Newtonsoft.Json;

namespace TrashCollector.Controllers
{
    public class CustomersController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: Customers1
        public ActionResult Index()
        {
            var currentUser = User.Identity.GetUserId();
            return View(db.Customer.Where(c => c.ApplicationUserId == currentUser));
        }

        // GET: Customers1/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Customer customer = db.Customer.Find(id);
            if (customer == null)
            {
                return HttpNotFound();
            }
            return View(customer);
        }

        public ActionResult AccountDetails(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Customer customer = db.Customer.Find(id);
            if (customer == null)
            {
                return HttpNotFound();
            }
            return View(customer);
        }

        public ActionResult PickupHistory()
        {
            var currentId = User.Identity.GetUserId();
            var currentUser = db.Customer.FirstOrDefault(c => c.ApplicationUserId == currentId);
            var currentCustomerId = currentUser.customerId;
            var listings = db.PickupTracker.Where(c => c.customerId == currentCustomerId).Include(c => c.Customer).Include(c => c.Employee);
            return View(listings);
        }
        public string ConvertAddressToGoogleFormat(Customer customer)
        {
            string googleFormatAddress = customer.streetAddress + "," + customer.city + "," + customer.stateAbbreviation + "," + customer.zipCode + ",USA";
            return googleFormatAddress;
        }

        public GeoCode GeoLocate(string address)
        {
            var requestUrl = $"https://maps.googleapis.com/maps/api/geocode/json?address={address}&key=AIzaSyCvNx58z28nAtRCUDGJU6xi2qisdrmE1dQ";
            var result = new WebClient().DownloadString(requestUrl);
            GeoCode geocode = JsonConvert.DeserializeObject<GeoCode>(result);
            return geocode;
        }

        // GET: Customers1/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Customers1/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "customerId,firstName,lastName,balance,pickupDay,speicalPickupDate,streetAddress,city,zipCode,ApplicationUserId,AccountSuspensionStartDate,AccountSuspensionEndDate,pickupDateSelected,pickupConfirmed,longitude,latitude,stateAbbreviation")] Customer customer)
        {
            if (ModelState.IsValid)
            {
                var currentUser = User.Identity.GetUserId();
                customer.ApplicationUserId = currentUser;
                customer.balance = 0.00;
                customer.specialPickupDate = null;
                customer.AccountSuspensionStartDate = null;
                customer.AccountSuspensionEndDate = null;
                customer.pickupConfirmed = false;
                string addressToConvert = ConvertAddressToGoogleFormat(customer);
                var geoLocate = GeoLocate(addressToConvert);
                customer.longitute = geoLocate.results[0].geometry.location.lng;
                customer.latitude = geoLocate.results[0].geometry.location.lat;
                db.Customer.Add(customer);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(customer);
        }

        // GET: Customers1/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Customer customer = db.Customer.Find(id);
            if (customer == null)
            {
                return HttpNotFound();
            }
            return View(customer);
        }

        // POST: Customers1/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "customerId,firstName,lastName,streetAddress,city,zipCode,pickupDay,speicalPickupDate,AccountSuspensionStartDate,AccountSuspensionEndDate,ApplicationUserId,longitute,latitude,stateAbbreviation,balance")] Customer customer)
        {
            if (ModelState.IsValid)
            {
                string addressToConvert = ConvertAddressToGoogleFormat(customer);
                var geoLocate = GeoLocate(addressToConvert);
                customer.longitute = geoLocate.results[0].geometry.location.lng;
                customer.latitude = geoLocate.results[0].geometry.location.lat;
                db.Entry(customer).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(customer);
        }

        // GET: Customers1/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Customer customer = db.Customer.Find(id);
            if (customer == null)
            {
                return HttpNotFound();
            }
            return View(customer);
        }

        // POST: Customers1/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Customer customer = db.Customer.Find(id);
            db.Customer.Remove(customer);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

TrashCollector/TrashCollector/Controllers/EmployeesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using Microsoft.AspNet.Identity;
using System.Linq;
using System.Net;
using System.Web;
using System.IO;
using System.Text;
using System.Web.Mvc;
using TrashCollector.Models;
using System.Xml.Linq;
using System.Web.Script;
using System.Configuration;
using Nest;
using System.Web.Script.Serialization;
using Newtonsoft.Json.Linq;
using Newtonsoft.Json;

namespace TrashCollector.Controllers
{
    public class EmployeesController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: Employees
        public ActionResult Index()
        {
            var currentUser = User.Identity.GetUserId();
            return View(db.Employee.Where(e => e.ApplicationUserId == currentUser));
        }

        // Method to retrieve customers scheduled for current day

        public List<Customer> GetCurrentDayCustomers()
        {
            var employeeId = User.Identity.GetUserId();
            var currentEmployee = db.Employee.Where(e => e.ApplicationUserId == employeeId).Single();
            var dayOfWeekToday = DateTime.Now.DayOfWeek.ToString();
            var dateToday = DateTime.Now;
            var customerZipCodeMatch = db.Customer.Where(c => c.zipCode == currentEmployee.zipCode && c.pickupDay == dayOfWeekToday || c.specialPickupDate == dateToday).ToList();
            var customerSuspensionRemoved = customerZipCodeMatch.Where(c => (c.AccountSuspensionStartDate > dateToday && c.AccountSuspensionEndDate < dateToday)
            || (c.AccountSuspensionEndDate == null && c.AccountSuspensionStartDate == null)).ToList();
            return customerSuspensionRemoved;
        }

        // GET: Employees/Details/5
        public ActionResult Details()
        {
            return View(GetCurrentDayCustomers());
        }

        // GET: Employees/AllCustomers
        public ActionResult AllCustomers()
        {
            var employeeId = User.Identity.GetUserId();
            var currentEmployee = db.Employee.Where(e => e.ApplicationUserId == employeeId).Single();
            var customerZipCodeMatch = db.Customer.Where(c => c.zipCode == currentEmployee.zipCode).ToList();
            return View(customerZipCodeMatch);
        }
        // GET: Employees/PickupSchedule
        public ActionResult PickupSchedule(string searchString)
        {
            var employeeId = User.Identity.GetUserId();
            var currentEmployee = db.Employee.Where(e => e.ApplicationUserId == employeeId).Single();
            var customerZipAndDayMatch = db.Customer.Where(c => c.zipCode == currentEmployee.zipCode && c.pickupDay == searchString).ToList();
            return View(customerZipAndDayMatch);
        }
        // GET: Employees/CustomerDetails
        public ActionResult CustomerDetails(int id)
        {
            var customerQuery = db.Customer.FirstOrDefault(c => c.customerId == id);
            return View(customerQuery);
        }


        // GET: Employees/ConfirmPickup
        public ActionResult ConfirmPickup(int id)
        {
            var customerToConfirm = db.Customer.FirstOrDefault(c => c.customerId == id);
            return View(customerToConfirm);
        }

        //POST: Employees/ConfirmPickup
       [HttpPost]
       [ValidateAntiForgeryToken]
        public ActionResult ConfirmPickup([Bind(Include = "customerId,firstName,lastName,balance,pickupDay,pickupDateSelected,Date,streetAddress,city,zipCode,ApplicationUserId,AccountSuspensionStartDate,AccountSuspensionEndDate,pickupDateSelected,pickupConfirmed,longitute,latitude")]Customer customer)
        {
            try
            {
                var currentUser = User.Identity.GetUserId();
                var currentEmployee = db.Employee.FirstOrDefault(e => e.ApplicationUserId == currentUser);
                PickupTracker newPickupListings = new PickupTracker();
                CreatePickupListing(newPickupListings, customer, currentEmployee);
                double weeklyTrashCharge = 10.00;
                customer.balance += weeklyTrashCharge;
                customer.pickupConfirmed = true;
                db.Entry(customer).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Details");
            }
            catch
            {
                return View();
            }
        }

        //GET: Employees/Complete Day
        public ActionResult CompleteDay()
        {
            var dailyCustomers = GetCurrentDayCustomers();
            return View(dailyCustomers);
        }

        //POST: Employees/Complete Day
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult CompleteDay(List<Customer> customers)
        {
            customers = GetCurrentDayCustomers();
            var customersCompletedPickups = customers.Where(c => c.pickupConfirmed == true);
            customers = customersCompletedPickups.Select(c => { c.pickupConfirmed = false; return c; }).ToList();
            foreach(var item in customers)
            {
                db.Entry(item).State = EntityState.Modified;
            }
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        public void CreatePickupListing([Bind(Include = "pickupDate,employeeId,customerId")]PickupTracker pickupTracker, Customer customer, Employee employee)
        {
            var customerToConfirm = customer.customerId;
            var employeeToConfirm = employee.employeeId;
            var dateOfConfirmation = DateTime.Now.Date;
            pickupTracker.pickupDate = dateOfConfirmation;
            pickupTracker.customerId = customerToConfirm;
            pickupTracker.employeeId = employeeToConfirm;
            db.PickupTracker.Add(pickupTracker);
            db.SaveChanges();
        }

        public ActionResult PickupListing()
        {
            var listings = db.PickupTracker.Include(c => c.Customer).Include(c => c.Employee);
            return View(listings);
        }


        // GET: Employees/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Employees/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "employeeId,zipCode,firstName,lastName,ApplicationUserId")] Employee employee)
        {
            if (ModelState.IsValid)
            {
                var currentUser = User.Identity.GetUserId();
                employee.ApplicationUserId = currentUser;
                db.Employee.Add(employee);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(employee);
        }

        // GET: Employees/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Employee employee = db.Employee.Find(id);
            if (employee == null)
            {
                return HttpNotFound();
            }
            return View(employee);
        }

        // POST: Employees/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "employeeId,firstName,lastName,zipCode,ApplicationUserId")] Employee employee)
        {
            if (ModelState.IsValid)
            {
                db.Entry(employee).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(employee);
        }

        // GET: Employees/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Employee employee = db.Employee.Find(id);
            if (employee == null)
            {
                return HttpNotFound();
            }
            return View(employee);
        }

        // POST: Employees/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Employee employee = db.Employee.Find(id);
            db.Employee.Remove(employee);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

TrashCollector/TrashCollector/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Trash Collector", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>

                </ul>
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

TrashCollector/TrashCollector/Views/Shared/_LayoutCustomer.cshtml
@{
    ViewBag.Title = "_LayoutCustomer";
}
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Customer Layout</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Trash Collector", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("Customer Account", "Index", "Customers")</li>
                </ul>
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

TrashCollector/TrashCollector/Views/Shared/_LayoutEmployee.cshtml
@{
    ViewBag.Title = "_LayoutEmployee";
}
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Employee Layout</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Trash Collector", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("Employee Account", "Index", "Employees")</li>
                    <li>@Html.ActionLink("Today's Pickups", "Details", "Employees")</li>
                    <li>@Html.ActionLink("Pickup Day Search", "PickupSchedule", "Employees")</li>
                    <li>@Html.ActionLink("Pickup Tracker", "PickupListing", "Employees")</li>
                </ul>
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>